### ISSUE TITLE
Demo Site not working properly

### ISSUE THREAD

**Issue by ghost** [withpulp/activity-tracker#1]
The demo site doesn't load first time. We have to wait for the site to load.

**Comment by dvzrd** [comment]
Hey,

I just deployed the latest commits. The tracker doesn't do anything yet, still working on it.

**Comment by hudat** [comment]
@bluebay out of curiosity - how'd you stumble onto the tracker? Let us know if you have a need/feature request. We can prioritize accordingly.

**Comment by ghost** [comment]
@hudat 

I did github search for "meteor activity" I guess. I exactly don't remember.
